server:
  port: 8080
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: group_id
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    schema-registry: http://schema-registry:8081
join:
  state:
    redis-host-name: 172.17.0.2
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com:
      fabiogouw: DEBUG