/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fabiogouw.eventprocessingapp.adapters.dtos;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FraudAnalysisResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4526872679600042326L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FraudAnalysisResult\",\"namespace\":\"com.fabiogouw.eventprocessingapp.adapters.dtos\",\"fields\":[{\"name\":\"correlationId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Id of the whole operation.\"},{\"name\":\"accountFrom\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Id of the account we will analyse.\"},{\"name\":\"result\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Result of the fraud analysis process.\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FraudAnalysisResult> ENCODER =
      new BinaryMessageEncoder<FraudAnalysisResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FraudAnalysisResult> DECODER =
      new BinaryMessageDecoder<FraudAnalysisResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FraudAnalysisResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FraudAnalysisResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FraudAnalysisResult>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FraudAnalysisResult to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FraudAnalysisResult from a ByteBuffer. */
  public static FraudAnalysisResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Id of the whole operation. */
  @Deprecated public java.lang.String correlationId;
  /** Id of the account we will analyse. */
  @Deprecated public java.lang.String accountFrom;
  /** Result of the fraud analysis process. */
  @Deprecated public java.lang.String result;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FraudAnalysisResult() {}

  /**
   * All-args constructor.
   * @param correlationId Id of the whole operation.
   * @param accountFrom Id of the account we will analyse.
   * @param result Result of the fraud analysis process.
   */
  public FraudAnalysisResult(java.lang.String correlationId, java.lang.String accountFrom, java.lang.String result) {
    this.correlationId = correlationId;
    this.accountFrom = accountFrom;
    this.result = result;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return correlationId;
    case 1: return accountFrom;
    case 2: return result;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: correlationId = (java.lang.String)value$; break;
    case 1: accountFrom = (java.lang.String)value$; break;
    case 2: result = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return Id of the whole operation.
   */
  public java.lang.String getCorrelationId() {
    return correlationId;
  }

  /**
   * Sets the value of the 'correlationId' field.
   * Id of the whole operation.
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.String value) {
    this.correlationId = value;
  }

  /**
   * Gets the value of the 'accountFrom' field.
   * @return Id of the account we will analyse.
   */
  public java.lang.String getAccountFrom() {
    return accountFrom;
  }

  /**
   * Sets the value of the 'accountFrom' field.
   * Id of the account we will analyse.
   * @param value the value to set.
   */
  public void setAccountFrom(java.lang.String value) {
    this.accountFrom = value;
  }

  /**
   * Gets the value of the 'result' field.
   * @return Result of the fraud analysis process.
   */
  public java.lang.String getResult() {
    return result;
  }

  /**
   * Sets the value of the 'result' field.
   * Result of the fraud analysis process.
   * @param value the value to set.
   */
  public void setResult(java.lang.String value) {
    this.result = value;
  }

  /**
   * Creates a new FraudAnalysisResult RecordBuilder.
   * @return A new FraudAnalysisResult RecordBuilder
   */
  public static com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder newBuilder() {
    return new com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder();
  }

  /**
   * Creates a new FraudAnalysisResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FraudAnalysisResult RecordBuilder
   */
  public static com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder newBuilder(com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder other) {
    return new com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder(other);
  }

  /**
   * Creates a new FraudAnalysisResult RecordBuilder by copying an existing FraudAnalysisResult instance.
   * @param other The existing instance to copy.
   * @return A new FraudAnalysisResult RecordBuilder
   */
  public static com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder newBuilder(com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult other) {
    return new com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder(other);
  }

  /**
   * RecordBuilder for FraudAnalysisResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FraudAnalysisResult>
    implements org.apache.avro.data.RecordBuilder<FraudAnalysisResult> {

    /** Id of the whole operation. */
    private java.lang.String correlationId;
    /** Id of the account we will analyse. */
    private java.lang.String accountFrom;
    /** Result of the fraud analysis process. */
    private java.lang.String result;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[0].schema(), other.correlationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountFrom)) {
        this.accountFrom = data().deepCopy(fields()[1].schema(), other.accountFrom);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.result)) {
        this.result = data().deepCopy(fields()[2].schema(), other.result);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FraudAnalysisResult instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[0].schema(), other.correlationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountFrom)) {
        this.accountFrom = data().deepCopy(fields()[1].schema(), other.accountFrom);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.result)) {
        this.result = data().deepCopy(fields()[2].schema(), other.result);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'correlationId' field.
      * Id of the whole operation.
      * @return The value.
      */
    public java.lang.String getCorrelationId() {
      return correlationId;
    }

    /**
      * Sets the value of the 'correlationId' field.
      * Id of the whole operation.
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder setCorrelationId(java.lang.String value) {
      validate(fields()[0], value);
      this.correlationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * Id of the whole operation.
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * Id of the whole operation.
      * @return This builder.
      */
    public com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountFrom' field.
      * Id of the account we will analyse.
      * @return The value.
      */
    public java.lang.String getAccountFrom() {
      return accountFrom;
    }

    /**
      * Sets the value of the 'accountFrom' field.
      * Id of the account we will analyse.
      * @param value The value of 'accountFrom'.
      * @return This builder.
      */
    public com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder setAccountFrom(java.lang.String value) {
      validate(fields()[1], value);
      this.accountFrom = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'accountFrom' field has been set.
      * Id of the account we will analyse.
      * @return True if the 'accountFrom' field has been set, false otherwise.
      */
    public boolean hasAccountFrom() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'accountFrom' field.
      * Id of the account we will analyse.
      * @return This builder.
      */
    public com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder clearAccountFrom() {
      accountFrom = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'result' field.
      * Result of the fraud analysis process.
      * @return The value.
      */
    public java.lang.String getResult() {
      return result;
    }

    /**
      * Sets the value of the 'result' field.
      * Result of the fraud analysis process.
      * @param value The value of 'result'.
      * @return This builder.
      */
    public com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder setResult(java.lang.String value) {
      validate(fields()[2], value);
      this.result = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'result' field has been set.
      * Result of the fraud analysis process.
      * @return True if the 'result' field has been set, false otherwise.
      */
    public boolean hasResult() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'result' field.
      * Result of the fraud analysis process.
      * @return This builder.
      */
    public com.fabiogouw.eventprocessingapp.adapters.dtos.FraudAnalysisResult.Builder clearResult() {
      result = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FraudAnalysisResult build() {
      try {
        FraudAnalysisResult record = new FraudAnalysisResult();
        record.correlationId = fieldSetFlags()[0] ? this.correlationId : (java.lang.String) defaultValue(fields()[0]);
        record.accountFrom = fieldSetFlags()[1] ? this.accountFrom : (java.lang.String) defaultValue(fields()[1]);
        record.result = fieldSetFlags()[2] ? this.result : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FraudAnalysisResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<FraudAnalysisResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FraudAnalysisResult>
    READER$ = (org.apache.avro.io.DatumReader<FraudAnalysisResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
